version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 0644

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: ./install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./start_application.sh
      timeout: 300
      runas: ec2-user
